from automata.fa.Moore import Moore

file = open("./inputs/test-001.cm")

moore = Moore(['q0', 'id', 'i', 'in', 'int','INT', 'int*', 'if', 'IF', 'if*', 'e','el', 'els', 'else', 'ELSE','else*', 'r', 're', 'ret', 'retu', 'retur', 'return', 'RETURN','return*', 
               'v', 'vo', 'voi', 'void', 'VOID', 'void*', 'w', 'wh', 'whi', 'whil', 'while', 'WHILE', 'while*', 'f', 'fl', 'flo', 'floa', 'float', 'FLOAT', 'float*', 'fo', 'for', 'FOR', 
               'for*', 'PLUS', 'MINUS', 'TIMES', 'DIVIDE', '<', 'LESS', 'LESS_EQUAL', '>', 'GREATER', 'GREATER_EQUAL', '=', 'ATTRIBUTION', 'EQUALS', '!', 'DIFFERENT', 'LPAREN', 'RPAREN', 
               'LBRACKETS', 'RBRACKETS', 'LBRACES', 'RBRACES', 'SEMICOLON', 'COMMA', 'num', 'NUMBER', 'SPACE', 'letters'], # estados
              
              ['+', '-', '*', '/', '<', '<=', '>', '>=', '==', '!=', '=', '(', ')', '[', ']', '{', '}', ';', ',', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 
              'i' , 'n', 't', 'f', 'l', 's', 'r', 'u', 'v', 'o', 'd', 'w', 'h', 'e', 'a', 'b', 'c', 'g', 'j', 'k', 'm', 'n', 'p', 'q', 'x', 'y', 'z', ' ', 'ç', '\n', '\t', '.'], #alfabeto
              
              ['IF', 'ELSE', 'INT', 'RETURN', 'VOID', 'WHILE', 'FOR', 'FLOAT', 'PLUS', 'MINUS', 'TIMES', 'DIVIDE', 'LESS', 'LESS_EQUAL', 'GREATER', 'GREATER_EQUAL', 'EQUALS', 'DIFFERENT', 
              'LPAREN', 'RPAREN', 'LBRACKETS', 'RBRACKETS', 'LBRACES', 'RBRACES', 'ATTRIBUTION', 'SEMICOLON', 'COMMA', 'NUMBER', 'ID'], # output tokens
              
              { # funções de transição
                
                'q0' : {
                    'i' : 'i', # int
                    'e' : 'e', # else
                    'r' : 'r', # return
                    'v' : 'v', # void
                    'w' : 'w', # while
                    'f' : 'f', # for / float

                    'a' : 'letters',
                    'b' : 'letters',
                    'c' : 'letters',
                    'd' : 'letters',
                    'e' : 'letters',
                    'g' : 'letters',
                    'h' : 'letters',
                    'j' : 'letters',
                    'k' : 'letters',
                    'l' : 'letters',
                    'm' : 'letters',
                    'n' : 'letters',
                    'o' : 'letters',
                    'p' : 'letters',
                    'q' : 'letters',
                    's' : 'letters',
                    't' : 'letters',
                    'u' : 'letters',
                    'x' : 'letters',
                    'y' : 'letters',
                    'z' : 'letters',

                    '+' : 'PLUS',
                    '-' : 'MINUS',
                    '*' : 'TIMES',
                    '/' : 'DIVIDE',
                    '<' : '<',
                    '>' : '>',
                    
                    '=' : '=',
                    '!' : '!',

                    '(' : 'LPAREN',
                    ')' : 'RPAREN',
                    '{' : 'LBRACES',
                    '}' : 'RBRACES',
                    '[' : 'LBRACKETS',
                    ']' : 'RBRACKETS',

                    ';' : 'SEMICOLON',
                    ',' : 'COMMA',

                    '0': 'num',
                    '1': 'num',
                    '2': 'num',
                    '3': 'num',
                    '4': 'num',
                    '5': 'num',
                    '6': 'num',
                    '7': 'num',
                    '8': 'num',
                    '9': 'num',

                    ' ' : 'SPACE',
                    'ç' : 'ç',
                    '\n' : '\n',
                    '\t' : '\t'
                },

                'id' : {
                    # token ID
                },
                
                'i' : {
                    'n': 'in',
                    'ç': 'id',
                    'f': 'if',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'in' : {
                    'ç': 'id',
                    't': 'int',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'int' : {
                    'ç': 'INT',
                    'a': 'int*',
                    'b': 'int*',
                    'c': 'int*',
                    'd': 'int*',
                    'e': 'int*',
                    'f': 'int*',
                    'g': 'int*',
                    'h': 'int*',
                    'i': 'int*',
                    'j': 'int*',
                    'k': 'int*',
                    'l': 'int*',
                    'm': 'int*',
                    'n': 'int*',
                    'o': 'int*',
                    'p': 'int*',
                    'q': 'int*',
                    'r': 'int*',
                    's': 'int*',
                    't': 'int*',
                    'u': 'int*',
                    'v': 'int*',
                    'w': 'int*',
                    'x': 'int*',
                    'y': 'int*',
                    'z': 'int*',

                    '0': 'int*',
                    '1': 'int*',
                    '2': 'int*',
                    '3': 'int*',
                    '4': 'int*',
                    '5': 'int*',
                    '6': 'int*',
                    '7': 'int*',
                    '8': 'int*',
                    '9': 'int*'
                },

                'int*' : {
                    'ç': 'id',
                    'a': 'int*',
                    'b': 'int*',
                    'c': 'int*',
                    'd': 'int*',
                    'e': 'int*',
                    'f': 'int*',
                    'g': 'int*',
                    'h': 'int*',
                    'i': 'int*',
                    'j': 'int*',
                    'k': 'int*',
                    'l': 'int*',
                    'm': 'int*',
                    'n': 'int*',
                    'o': 'int*',
                    'p': 'int*',
                    'q': 'int*',
                    'r': 'int*',
                    's': 'int*',
                    't': 'int*',
                    'u': 'int*',
                    'v': 'int*',
                    'w': 'int*',
                    'x': 'int*',
                    'y': 'int*',
                    'z': 'int*',

                    '0': 'int*',
                    '1': 'int*',
                    '2': 'int*',
                    '3': 'int*',
                    '4': 'int*',
                    '5': 'int*',
                    '6': 'int*',
                    '7': 'int*',
                    '8': 'int*',
                    '9': 'int*'
                },

                'INT' : {
                    # token INT
                },

                'if' : {
                    'ç': 'IF',
                    'a': 'if*',
                    'b': 'if*',
                    'c': 'if*',
                    'd': 'if*',
                    'e': 'if*',
                    'f': 'if*',
                    'g': 'if*',
                    'h': 'if*',
                    'i': 'if*',
                    'j': 'if*',
                    'k': 'if*',
                    'l': 'if*',
                    'm': 'if*',
                    'n': 'if*',
                    'o': 'if*',
                    'p': 'if*',
                    'q': 'if*',
                    'r': 'if*',
                    's': 'if*',
                    't': 'if*',
                    'u': 'if*',
                    'v': 'if*',
                    'w': 'if*',
                    'x': 'if*',
                    'y': 'if*',
                    'z': 'if*',

                    '0': 'if*',
                    '1': 'if*',
                    '2': 'if*',
                    '3': 'if*',
                    '4': 'if*',
                    '5': 'if*',
                    '6': 'if*',
                    '7': 'if*',
                    '8': 'if*',
                    '9': 'if*'
                },

                'if*':{
                    'ç': 'ID',
                    'a': 'if*',
                    'b': 'if*',
                    'c': 'if*',
                    'd': 'if*',
                    'e': 'if*',
                    'f': 'if*',
                    'g': 'if*',
                    'h': 'if*',
                    'i': 'if*',
                    'j': 'if*',
                    'k': 'if*',
                    'l': 'if*',
                    'm': 'if*',
                    'n': 'if*',
                    'o': 'if*',
                    'p': 'if*',
                    'q': 'if*',
                    'r': 'if*',
                    's': 'if*',
                    't': 'if*',
                    'u': 'if*',
                    'v': 'if*',
                    'w': 'if*',
                    'x': 'if*',
                    'y': 'if*',
                    'z': 'if*',

                    '0': 'if*',
                    '1': 'if*',
                    '2': 'if*',
                    '3': 'if*',
                    '4': 'if*',
                    '5': 'if*',
                    '6': 'if*',
                    '7': 'if*',
                    '8': 'if*',
                    '9': 'if*'
                },

                'e' : {
                    'ç': 'id',
                    'l' : 'el',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'el' : {
                    'ç' : 'id',
                    's' : 'els',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'els' : {
                    'ç' : 'id',
                    'e' : 'else',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'else' : {
                    'ç' : 'ELSE',
                    'a': 'else*',
                    'b': 'else*',
                    'c': 'else*',
                    'd': 'else*',
                    'e': 'else*',
                    'f': 'else*',
                    'g': 'else*',
                    'h': 'else*',
                    'i': 'else*',
                    'j': 'else*',
                    'k': 'else*',
                    'l': 'else*',
                    'm': 'else*',
                    'n': 'else*',
                    'o': 'else*',
                    'p': 'else*',
                    'q': 'else*',
                    'r': 'else*',
                    's': 'else*',
                    't': 'else*',
                    'u': 'else*',
                    'v': 'else*',
                    'w': 'else*',
                    'x': 'else*',
                    'y': 'else*',
                    'z': 'else*',

                    '0': 'else*',
                    '1': 'else*',
                    '2': 'else*',
                    '3': 'else*',
                    '4': 'else*',
                    '5': 'else*',
                    '6': 'else*',
                    '7': 'else*',
                    '8': 'else*',
                    '9': 'else*'
                },

                'ELSE' : {
                    # token ELSE
                },

                'else*' : {
                    'ç' : 'id',
                    'a': 'else*',
                    'b': 'else*',
                    'c': 'else*',
                    'd': 'else*',
                    'e': 'else*',
                    'f': 'else*',
                    'g': 'else*',
                    'h': 'else*',
                    'i': 'else*',
                    'j': 'else*',
                    'k': 'else*',
                    'l': 'else*',
                    'm': 'else*',
                    'n': 'else*',
                    'o': 'else*',
                    'p': 'else*',
                    'q': 'else*',
                    'r': 'else*',
                    's': 'else*',
                    't': 'else*',
                    'u': 'else*',
                    'v': 'else*',
                    'w': 'else*',
                    'x': 'else*',
                    'y': 'else*',
                    'z': 'else*',

                    '0': 'else*',
                    '1': 'else*',
                    '2': 'else*',
                    '3': 'else*',
                    '4': 'else*',
                    '5': 'else*',
                    '6': 'else*',
                    '7': 'else*',
                    '8': 'else*',
                    '9': 'else*'
                },

                'r' : {
                    'ç' : 'id',
                    'e' : 're',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                're' : {
                    'ç' : 'id',
                    't' : 'ret',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'ret' : {
                    'ç' : 'id',
                    'u' : 'retu',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'retu' : {
                    'ç' : 'id',
                    'r' : 'retur',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'retur' : {
                    'ç' : 'id',
                    'n' : 'return',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'return' : {
                    'ç' : 'RETURN',
                    'a': 'return*',
                    'b': 'return*',
                    'c': 'return*',
                    'd': 'return*',
                    'e': 'return*',
                    'f': 'return*',
                    'g': 'return*',
                    'h': 'return*',
                    'i': 'return*',
                    'j': 'return*',
                    'k': 'return*',
                    'l': 'return*',
                    'm': 'return*',
                    'n': 'return*',
                    'o': 'return*',
                    'p': 'return*',
                    'q': 'return*',
                    'r': 'return*',
                    's': 'return*',
                    't': 'return*',
                    'u': 'return*',
                    'v': 'return*',
                    'w': 'return*',
                    'x': 'return*',
                    'y': 'return*',
                    'z': 'return*',

                    '0': 'return*',
                    '1': 'return*',
                    '2': 'return*',
                    '3': 'return*',
                    '4': 'return*',
                    '5': 'return*',
                    '6': 'return*',
                    '7': 'return*',
                    '8': 'return*',
                    '9': 'return*'
                },

                'RETURN' : {
                    # token RETURN
                },

                'return*' : {
                    'ç' : 'id',
                    'a': 'return*',
                    'b': 'return*',
                    'c': 'return*',
                    'd': 'return*',
                    'e': 'return*',
                    'f': 'return*',
                    'g': 'return*',
                    'h': 'return*',
                    'i': 'return*',
                    'j': 'return*',
                    'k': 'return*',
                    'l': 'return*',
                    'm': 'return*',
                    'n': 'return*',
                    'o': 'return*',
                    'p': 'return*',
                    'q': 'return*',
                    'r': 'return*',
                    's': 'return*',
                    't': 'return*',
                    'u': 'return*',
                    'v': 'return*',
                    'w': 'return*',
                    'x': 'return*',
                    'y': 'return*',
                    'z': 'return*',

                    '0': 'return*',
                    '1': 'return*',
                    '2': 'return*',
                    '3': 'return*',
                    '4': 'return*',
                    '5': 'return*',
                    '6': 'return*',
                    '7': 'return*',
                    '8': 'return*',
                    '9': 'return*'
                },

                'v' : {
                    'ç' : 'id',
                    'o' : 'vo',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'vo' : {
                    'ç' : 'id',
                    'i' : 'voi',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'voi' : {
                    'ç' : 'id',
                    'd' : 'void',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'void' : {
                    'ç' : 'VOID',
                    'a': 'void*',
                    'b': 'void*',
                    'c': 'void*',
                    'd': 'void*',
                    'e': 'void*',
                    'f': 'void*',
                    'g': 'void*',
                    'h': 'void*',
                    'i': 'void*',
                    'j': 'void*',
                    'k': 'void*',
                    'l': 'void*',
                    'm': 'void*',
                    'n': 'void*',
                    'o': 'void*',
                    'p': 'void*',
                    'q': 'void*',
                    'r': 'void*',
                    's': 'void*',
                    't': 'void*',
                    'u': 'void*',
                    'v': 'void*',
                    'w': 'void*',
                    'x': 'void*',
                    'y': 'void*',
                    'z': 'void*',

                    '0': 'void*',
                    '1': 'void*',
                    '2': 'void*',
                    '3': 'void*',
                    '4': 'void*',
                    '5': 'void*',
                    '6': 'void*',
                    '7': 'void*',
                    '8': 'void*',
                    '9': 'void*'
                },

                'VOID' : {
                    # token VOID
                },

                'void*' : {
                    'ç' : 'id',
                    'a': 'void*',
                    'b': 'void*',
                    'c': 'void*',
                    'd': 'void*',
                    'e': 'void*',
                    'f': 'void*',
                    'g': 'void*',
                    'h': 'void*',
                    'i': 'void*',
                    'j': 'void*',
                    'k': 'void*',
                    'l': 'void*',
                    'm': 'void*',
                    'n': 'void*',
                    'o': 'void*',
                    'p': 'void*',
                    'q': 'void*',
                    'r': 'void*',
                    's': 'void*',
                    't': 'void*',
                    'u': 'void*',
                    'v': 'void*',
                    'w': 'void*',
                    'x': 'void*',
                    'y': 'void*',
                    'z': 'void*',

                    '0': 'void*',
                    '1': 'void*',
                    '2': 'void*',
                    '3': 'void*',
                    '4': 'void*',
                    '5': 'void*',
                    '6': 'void*',
                    '7': 'void*',
                    '8': 'void*',
                    '9': 'void*'
                },

                'w' : {
                    'ç' : 'id',
                    'h' : 'wh',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'wh' : {
                    'ç' : 'id',
                    'i' : 'whi',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'whi' : {
                    'ç' : 'id',
                    'l' : 'whil',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },
                
                'whil' : {
                    'ç' : 'id',
                    'e' : 'while',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'while' : {
                    'ç' : 'WHILE',
                    'a': 'while*',
                    'b': 'while*',
                    'c': 'while*',
                    'd': 'while*',
                    'e': 'while*',
                    'f': 'while*',
                    'g': 'while*',
                    'h': 'while*',
                    'i': 'while*',
                    'j': 'while*',
                    'k': 'while*',
                    'l': 'while*',
                    'm': 'while*',
                    'n': 'while*',
                    'o': 'while*',
                    'p': 'while*',
                    'q': 'while*',
                    'r': 'while*',
                    's': 'while*',
                    't': 'while*',
                    'u': 'while*',
                    'v': 'while*',
                    'w': 'while*',
                    'x': 'while*',
                    'y': 'while*',
                    'z': 'while*',

                    '0': 'while*',
                    '1': 'while*',
                    '2': 'while*',
                    '3': 'while*',
                    '4': 'while*',
                    '5': 'while*',
                    '6': 'while*',
                    '7': 'while*',
                    '8': 'while*',
                    '9': 'while*'
                },

                'WHILE' : {
                    # token WHILE
                },

                'while*' : {
                    'ç' : 'id',
                    'a': 'while*',
                    'b': 'while*',
                    'c': 'while*',
                    'd': 'while*',
                    'e': 'while*',
                    'f': 'while*',
                    'g': 'while*',
                    'h': 'while*',
                    'i': 'while*',
                    'j': 'while*',
                    'k': 'while*',
                    'l': 'while*',
                    'm': 'while*',
                    'n': 'while*',
                    'o': 'while*',
                    'p': 'while*',
                    'q': 'while*',
                    'r': 'while*',
                    's': 'while*',
                    't': 'while*',
                    'u': 'while*',
                    'v': 'while*',
                    'w': 'while*',
                    'x': 'while*',
                    'y': 'while*',
                    'z': 'while*',

                    '0': 'while*',
                    '1': 'while*',
                    '2': 'while*',
                    '3': 'while*',
                    '4': 'while*',
                    '5': 'while*',
                    '6': 'while*',
                    '7': 'while*',
                    '8': 'while*',
                    '9': 'while*'
                },
                
                'f' : {
                    'ç' : 'id',
                    'l' : 'fl',
                    'o' : 'fo',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'fl' : {
                    'ç' : 'id',
                    'o' : 'flo',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'flo' : {
                    'ç' : 'id',
                    'a' : 'floa',

                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },
                
                'floa' : {
                    'ç' : 'id',
                    't' : 'float',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'float' : {
                    'ç' : 'FLOAT',
                    'a': 'float*',
                    'b': 'float*',
                    'c': 'float*',
                    'd': 'float*',
                    'e': 'float*',
                    'f': 'float*',
                    'g': 'float*',
                    'h': 'float*',
                    'i': 'float*',
                    'j': 'float*',
                    'k': 'float*',
                    'l': 'float*',
                    'm': 'float*',
                    'n': 'float*',
                    'o': 'float*',
                    'p': 'float*',
                    'q': 'float*',
                    'r': 'float*',
                    's': 'float*',
                    't': 'float*',
                    'u': 'float*',
                    'v': 'float*',
                    'w': 'float*',
                    'x': 'float*',
                    'y': 'float*',
                    'z': 'float*',

                    '0': 'float*',
                    '1': 'float*',
                    '2': 'float*',
                    '3': 'float*',
                    '4': 'float*',
                    '5': 'float*',
                    '6': 'float*',
                    '7': 'float*',
                    '8': 'float*',
                    '9': 'float*'
                },

                'FLOAT' : {
                    # token FLOAT
                },

                'float*' : {
                    'ç' : 'id',
                    'a': 'float*',
                    'b': 'float*',
                    'c': 'float*',
                    'd': 'float*',
                    'e': 'float*',
                    'f': 'float*',
                    'g': 'float*',
                    'h': 'float*',
                    'i': 'float*',
                    'j': 'float*',
                    'k': 'float*',
                    'l': 'float*',
                    'm': 'float*',
                    'n': 'float*',
                    'o': 'float*',
                    'p': 'float*',
                    'q': 'float*',
                    'r': 'float*',
                    's': 'float*',
                    't': 'float*',
                    'u': 'float*',
                    'v': 'float*',
                    'w': 'float*',
                    'x': 'float*',
                    'y': 'float*',
                    'z': 'float*',

                    '0': 'float*',
                    '1': 'float*',
                    '2': 'float*',
                    '3': 'float*',
                    '4': 'float*',
                    '5': 'float*',
                    '6': 'float*',
                    '7': 'float*',
                    '8': 'float*',
                    '9': 'float*'
                },

                'fo' : {
                    'ç' : 'id',
                    'r' : 'for',

                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'for' : {
                    'ç' : 'FOR',
                    'a': 'for*',
                    'b': 'for*',
                    'c': 'for*',
                    'd': 'for*',
                    'e': 'for*',
                    'f': 'for*',
                    'g': 'for*',
                    'h': 'for*',
                    'i': 'for*',
                    'j': 'for*',
                    'k': 'for*',
                    'l': 'for*',
                    'm': 'for*',
                    'n': 'for*',
                    'o': 'for*',
                    'p': 'for*',
                    'q': 'for*',
                    'r': 'for*',
                    's': 'for*',
                    't': 'for*',
                    'u': 'for*',
                    'v': 'for*',
                    'w': 'for*',
                    'x': 'for*',
                    'y': 'for*',
                    'z': 'for*',

                    '0': 'for*',
                    '1': 'for*',
                    '2': 'for*',
                    '3': 'for*',
                    '4': 'for*',
                    '5': 'for*',
                    '6': 'for*',
                    '7': 'for*',
                    '8': 'for*',
                    '9': 'for*'
                },

                'FOR' : {
                   # token FOR
                },

                'for*' : {
                   'ç' : 'id',
                    'a': 'for*',
                    'b': 'for*',
                    'c': 'for*',
                    'd': 'for*',
                    'e': 'for*',
                    'f': 'for*',
                    'g': 'for*',
                    'h': 'for*',
                    'i': 'for*',
                    'j': 'for*',
                    'k': 'for*',
                    'l': 'for*',
                    'm': 'for*',
                    'n': 'for*',
                    'o': 'for*',
                    'p': 'for*',
                    'q': 'for*',
                    'r': 'for*',
                    's': 'for*',
                    't': 'for*',
                    'u': 'for*',
                    'v': 'for*',
                    'w': 'for*',
                    'x': 'for*',
                    'y': 'for*',
                    'z': 'for*',

                    '0': 'for*',
                    '1': 'for*',
                    '2': 'for*',
                    '3': 'for*',
                    '4': 'for*',
                    '5': 'for*',
                    '6': 'for*',
                    '7': 'for*',
                    '8': 'for*',
                    '9': 'for*'
                },

                'PLUS' : {
                    # token PLUS
                    'ç': 'ç'
                },

                'MINUS' : {
                    # token MINUS
                    'ç': 'ç'
                },

                'TIMES' : {
                    # token TIMES
                    'ç': 'ç'
                },

                'DIVIDE' : {
                    # token DIVIDE
                    'ç': 'ç'
                },

                '<' : {
                    'ç' : 'LESS',
                    '=' : 'LESS_EQUAL'
                },

                'LESS' : {
                    # token LESS
                    'ç': 'ç'
                },

                'LESS_EQUAL' : {
                    # token LESS_EQUAL
                    'ç': 'ç'
                },
                
                '>' : {
                    'ç': 'GREATER',
                    '=' : 'GREATER_EQUAL'
                },

                'GREATER' : {
                    # token GREATER
                    'ç': 'ç'
                },
                
                'GREATER_EQUAL' : {
                    # token LESS_EQUAL
                    'ç': 'ç'
                },

                '>=' : {
                    # token GREATER_EQUAL
                    'ç': 'ç'
                },
                
                '=' : {
                    'ç' : 'ATTRIBUTION',
                    '=' : 'EQUALS'
                },

                'ATTRIBUTION' : {
                    # token ATTRIBUTION
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'EQUALS' : {
                    # token EQUALS
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                '!' : {
                    '=' : 'DIFFERENT',
                    'ç': 'ç'
                    
                },
                
                'DIFFERENT' : {
                    # token DIFFERENT
                    'ç': 'ç'
                },

                'LPAREN': {
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'RPAREN' : {
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },
                
                'LBRACKETS' : {
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },
                
                'RBRACKETS' : {
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },
                
                'LBRACES': {
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },
                
                'RBRACES' : {
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                }, 

                'SEMICOLON' : {
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },
                
                'COMMA' : {
                    'ç': 'ç',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'num' : {
                    'ç': 'NUMBER',
                    '0': 'num',
                    '1': 'num',
                    '2': 'num',
                    '3': 'num',
                    '4': 'num',
                    '5': 'num',
                    '6': 'num',
                    '7': 'num',
                    '8': 'num',
                    '9': 'num',
                    '.' : 'num'
                },

                'NUMBER' : {
                    'ç': 'ç'
                },

                'SPACE' : {
                    'ç': 'ç'
                },

                'letters' : {
                    'ç' : 'id',
                    'a': 'letters',
                    'b': 'letters',
                    'c': 'letters',
                    'd': 'letters',
                    'e': 'letters',
                    'f': 'letters',
                    'g': 'letters',
                    'h': 'letters',
                    'i': 'letters',
                    'j': 'letters',
                    'k': 'letters',
                    'l': 'letters',
                    'm': 'letters',
                    'n': 'letters',
                    'o': 'letters',
                    'p': 'letters',
                    'q': 'letters',
                    'r': 'letters',
                    's': 'letters',
                    't': 'letters',
                    'u': 'letters',
                    'v': 'letters',
                    'w': 'letters',
                    'x': 'letters',
                    'y': 'letters',
                    'z': 'letters',

                    '0': 'letters',
                    '1': 'letters',
                    '2': 'letters',
                    '3': 'letters',
                    '4': 'letters',
                    '5': 'letters',
                    '6': 'letters',
                    '7': 'letters',
                    '8': 'letters',
                    '9': 'letters'
                },

                'ç' : {

                },

                '\n' : {
                    'ç': 'ç'
                },

                '\t' : {
                    'ç': 'ç'
                }
              
              
              },


            'q0',
            
                {
                'q0' : '',
                'id' : 'ID',
                'i' : '',
                'in' : '',
                'int' : '',
                'INT' : 'INT',
                'int*' : '',
                'if' : '',
                'IF' : 'IF',
                'e' : '',
                'el' : '',
                'els' : '',
                'else' : '',
                'ELSE' : 'ELSE',
                'else*' : '',
                'v' : '',
                'vo' : '',
                'voi' : '',
                'void' : '',
                'VOID' : 'VOID',
                'void*' : '',
                'r' : '',
                're' : '',
                'ret' : '',
                'retu' : '',
                'retur' : '',
                'return' : '',
                'RETURN' : 'RETURN',
                'return*' : '',
                'w' : '',
                'wh' : '',
                'whi' : '',
                'whil' : '',
                'while' : '',
                'WHILE' : 'WHILE',
                'while*' : '',
                'f' : '',
                'fl' : '',
                'flo' : '',
                'floa' : '',
                'float' : '',
                'FLOAT' : 'FLOAT',
                'float*' : '',
                'fo' : '',
                'for' : '',
                'FOR' : 'FOR',
                'for*' : '',
                'PLUS' : 'PLUS',
                'MINUS' : 'MINUS',
                'TIMES' : 'TIMES',
                'DIVIDE' : 'DIVIDE',
                '<' : '',
                'LESS' : 'LESS',
                'LESS_EQUAL' : 'LESS_EQUAL',
                '>' : '',
                'GREATER' : 'GREATER',
                'GREATER_EQUAL' : 'GREATER_EQUAL',
                '=' : '',
                'ATTRIBUTION' : 'ATTRIBUTION',
                'EQUALS' : 'EQUALS',
                '!' : '',
                'DIFFERENT' : 'DIFFERENT',
                'LPAREN' : 'LPAREN',
                'RPAREN' : 'RPAREN',
                'LBRACKETS' : 'LBRACKETS',
                'RBRACKETS' : 'RBRACKETS',
                'LBRACES' : 'LBRACES',
                'RBRACES' : 'RBRACES',
                'SEMICOLON' : 'SEMICOLON',
                'COMMA' : 'COMMA',
                'num' : '',
                'NUMBER' : 'NUMBER',
                'SPACE' : '',
                'letters' : '',
                'ç' : '',
                '\n': '',
                '\t' : ''
                }
)

print(moore)

separators = [' ', '(', ')', '[', ']', '{', '}', ',', ';', '\n', '\t']
buff = ''
sep_size = len(separators)

for line in file:
    for char in line:
        if char not in separators:
            buff += char
        if char in separators:
            buff += 'ç'
            print(moore.get_output_from_string(buff))
            print(moore.get_output_from_string(char))
            buff = ''
                
